server:
  port: 8082

spring:
  profiles:
    active: dev

  #thymeleaf配置
  thymeleaf:
    cache: false # 关闭页面缓存
    encoding: UTF-8 # 模板编码
    prefix: classpath:/templates/  # 页面映射路径
    suffix: .html # 试图后的后缀
    mode: HTML5 # 模板模式
  #本地数据库连接
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ice
    username: root
    password: 123456
  #图片上传大小配置
  servlet:
    multipart:
      # 最大支持文件大小
      max-file-size: 1000MB
      # 最大支持请求大小
      max-request-size: 1000MB
#静态资源的路径添加:直接写在该文件中是没有用的，还需要把它添加到MVC请求路径之中。同时不推荐直接写入resources文件夹中
#resourceLocations: C:/bishe/taskImages/
resourceLocations: /home/ubuntu/ice/bishe/taskImages/

ice:
  app: 1
  rmi:
    port: 8210
    server: 127.0.0.1:8212
    communicate-port: 18210
  pool:
    core-size: 4
    max-size: 4
    keep-alive-seconds: 60
    queue-capacity: 60000
test:
  value: 123
environment: dev



